dist: trusty
sudo: required
language: go

install:
 - go get -t -v ./...
 - go get -v -tags sqlite github.com/gobuffalo/pop/soda

before_script:
  - soda create -e $SODA_DIALECT
  - soda migrate -e $SODA_DIALECT

script:
  - go test -tags sqlite ./... -v

global_env:
  - MYSQL_USER="travis"
  - MYSQL_PASSWORD=""
  - POSTGRES_PASSWORD=""

.mysql: &mysql
  services:
    - mysql
  addons:
    apt:
      sources:
        - mysql-5.7-trusty
      packages:
        - mysql-server

.postgres: &postgres
  addons:
    postgresql: "9.5"

.mariadb: &mariadb
  addons:
    mariadb: '10.0'

.mssqlserver: &mssqlserver
  services:
    - docker
  before_install:
    - docker pull microsoft/mssql-server-linux
    - docker run -d -p 1433:1433 --name=mssqlserver microsoft/mssql-server-linux -e SA_PASSWORD=Tt@12345678 -e MSSQLSERVER_PASSWORD=Tt@12345678 -e ACCEPT_EULA=Y
    - sleep 4 # Wait for mssqlserver to be online
  after_script:
    - docker rm -f mssqlserver

matrix:
  include:
    - dist: trusty
      go: 1.9
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="sqlserver"
      <<: *mssqlserver
    - dist: trusty
      go: "1.10"
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="sqlserver"
      <<: *mssqlserver
    - dist: trusty
      go: "1.11"
      env: SODA_DIALECT="sqlite"
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="postgres"
      <<: *postgres
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="mysql_travis"
      <<: *mysql
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="sqlserver"
      <<: *mssqlserver
    - dist: trusty
      go: "tip"
      env: SODA_DIALECT="sqlite"
  allow_failures:
    - go: 'tip'